/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectsSubmitRouteImport } from './routes/projects/submit'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as LearnResearchRouteImport } from './routes/learn/research'
import { Route as LearnMarketingRouteImport } from './routes/learn/marketing'
import { Route as LearnDesignRouteImport } from './routes/learn/design'
import { Route as LearnContentCreationRouteImport } from './routes/learn/content-creation'
import { Route as LearnCommunityManagementRouteImport } from './routes/learn/community-management'
import { Route as EventsRequestRouteImport } from './routes/events/request'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin/opportunities'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminLearnRouteImport } from './routes/admin/learn'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsSubmitRoute = ProjectsSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnResearchRoute = LearnResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => LearnRoute,
} as any)
const LearnMarketingRoute = LearnMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => LearnRoute,
} as any)
const LearnDesignRoute = LearnDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => LearnRoute,
} as any)
const LearnContentCreationRoute = LearnContentCreationRouteImport.update({
  id: '/content-creation',
  path: '/content-creation',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCommunityManagementRoute =
  LearnCommunityManagementRouteImport.update({
    id: '/community-management',
    path: '/community-management',
    getParentRoute: () => LearnRoute,
  } as any)
const EventsRequestRoute = EventsRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnRoute = AdminLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/learn': typeof AdminLearnRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/request': typeof EventsRequestRoute
  '/learn/community-management': typeof LearnCommunityManagementRoute
  '/learn/content-creation': typeof LearnContentCreationRoute
  '/learn/design': typeof LearnDesignRoute
  '/learn/marketing': typeof LearnMarketingRoute
  '/learn/research': typeof LearnResearchRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/submit': typeof ProjectsSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/learn': typeof AdminLearnRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/request': typeof EventsRequestRoute
  '/learn/community-management': typeof LearnCommunityManagementRoute
  '/learn/content-creation': typeof LearnContentCreationRoute
  '/learn/design': typeof LearnDesignRoute
  '/learn/marketing': typeof LearnMarketingRoute
  '/learn/research': typeof LearnResearchRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/submit': typeof ProjectsSubmitRoute
  '/admin': typeof AdminIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/join': typeof JoinRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/opportunities': typeof OpportunitiesRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/learn': typeof AdminLearnRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/request': typeof EventsRequestRoute
  '/learn/community-management': typeof LearnCommunityManagementRoute
  '/learn/content-creation': typeof LearnContentCreationRoute
  '/learn/design': typeof LearnDesignRoute
  '/learn/marketing': typeof LearnMarketingRoute
  '/learn/research': typeof LearnResearchRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/submit': typeof ProjectsSubmitRoute
  '/admin/': typeof AdminIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/events'
    | '/join'
    | '/leaderboard'
    | '/learn'
    | '/opportunities'
    | '/partners'
    | '/profile'
    | '/projects'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/leaderboard'
    | '/admin/learn'
    | '/admin/members'
    | '/admin/opportunities'
    | '/admin/partners'
    | '/admin/projects'
    | '/admin/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/events/request'
    | '/learn/community-management'
    | '/learn/content-creation'
    | '/learn/design'
    | '/learn/marketing'
    | '/learn/research'
    | '/members/$memberId'
    | '/projects/$projectId'
    | '/projects/submit'
    | '/admin/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/events'
    | '/join'
    | '/leaderboard'
    | '/opportunities'
    | '/partners'
    | '/profile'
    | '/projects'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/leaderboard'
    | '/admin/learn'
    | '/admin/members'
    | '/admin/opportunities'
    | '/admin/partners'
    | '/admin/projects'
    | '/admin/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/events/request'
    | '/learn/community-management'
    | '/learn/content-creation'
    | '/learn/design'
    | '/learn/marketing'
    | '/learn/research'
    | '/members/$memberId'
    | '/projects/$projectId'
    | '/projects/submit'
    | '/admin'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/events'
    | '/join'
    | '/leaderboard'
    | '/learn'
    | '/opportunities'
    | '/partners'
    | '/profile'
    | '/projects'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/leaderboard'
    | '/admin/learn'
    | '/admin/members'
    | '/admin/opportunities'
    | '/admin/partners'
    | '/admin/projects'
    | '/admin/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/events/request'
    | '/learn/community-management'
    | '/learn/content-creation'
    | '/learn/design'
    | '/learn/marketing'
    | '/learn/research'
    | '/members/$memberId'
    | '/projects/$projectId'
    | '/projects/submit'
    | '/admin/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  JoinRoute: typeof JoinRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearnRoute: typeof LearnRouteWithChildren
  OpportunitiesRoute: typeof OpportunitiesRoute
  PartnersRoute: typeof PartnersRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  MembersMemberIdRoute: typeof MembersMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/submit': {
      id: '/projects/submit'
      path: '/submit'
      fullPath: '/projects/submit'
      preLoaderRoute: typeof ProjectsSubmitRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/research': {
      id: '/learn/research'
      path: '/research'
      fullPath: '/learn/research'
      preLoaderRoute: typeof LearnResearchRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/marketing': {
      id: '/learn/marketing'
      path: '/marketing'
      fullPath: '/learn/marketing'
      preLoaderRoute: typeof LearnMarketingRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/design': {
      id: '/learn/design'
      path: '/design'
      fullPath: '/learn/design'
      preLoaderRoute: typeof LearnDesignRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/content-creation': {
      id: '/learn/content-creation'
      path: '/content-creation'
      fullPath: '/learn/content-creation'
      preLoaderRoute: typeof LearnContentCreationRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/community-management': {
      id: '/learn/community-management'
      path: '/community-management'
      fullPath: '/learn/community-management'
      preLoaderRoute: typeof LearnCommunityManagementRouteImport
      parentRoute: typeof LearnRoute
    }
    '/events/request': {
      id: '/events/request'
      path: '/request'
      fullPath: '/events/request'
      preLoaderRoute: typeof EventsRequestRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learn': {
      id: '/admin/learn'
      path: '/learn'
      fullPath: '/admin/learn'
      preLoaderRoute: typeof AdminLearnRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLearnRoute: typeof AdminLearnRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLearnRoute: AdminLearnRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsRequestRoute: typeof EventsRequestRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsRequestRoute: EventsRequestRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface LearnRouteChildren {
  LearnCommunityManagementRoute: typeof LearnCommunityManagementRoute
  LearnContentCreationRoute: typeof LearnContentCreationRoute
  LearnDesignRoute: typeof LearnDesignRoute
  LearnMarketingRoute: typeof LearnMarketingRoute
  LearnResearchRoute: typeof LearnResearchRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCommunityManagementRoute: LearnCommunityManagementRoute,
  LearnContentCreationRoute: LearnContentCreationRoute,
  LearnDesignRoute: LearnDesignRoute,
  LearnMarketingRoute: LearnMarketingRoute,
  LearnResearchRoute: LearnResearchRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsSubmitRoute: typeof ProjectsSubmitRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsSubmitRoute: ProjectsSubmitRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearnRoute: LearnRouteWithChildren,
  OpportunitiesRoute: OpportunitiesRoute,
  PartnersRoute: PartnersRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  MembersMemberIdRoute: MembersMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
